### ISSUE TITLE
升级3.4.6问题依旧

### ISSUE THREAD

**Issue by dacapoday** [chinakids/atom-simplified-chinese-menu#17]
新开一个空文本，未保存关闭，对话框选择不保存后就会报错，和3.4.5一样的错误信息
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Unknown Windows Version
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.4.6

### Stack Trace

Uncaught TypeError: Cannot read property 'getAttribute' of null

```
At /C:/Users/dacap/.atom/packages/simplified-chinese-menu/lib/main.coffee:34

TypeError: Cannot read property 'getAttribute' of null
    at file:///C:/Users/dacap/.atom/packages/simplified-chinese-menu/lib/main.coffee:32:36
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.removeItem (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:387:16)
    at Pane.module.exports.Pane.destroyItem (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\src\pane.js:453:16)
    at atom-tabs.TabBarView.onClick (C:\Users\dacap\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:695:17)
```

### Commands

```
     -0:05.7.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "vim-mode",
      "autosave"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.0
emmet, v2.4.1
new-tab, v0.5.0
simplified-chinese-menu, v3.4.6

# Dev
No dev packages
```

**Comment by chinakids** [comment]
我的失误  我看成这个问题和另一个问题是同样的问题了   你这个确实是遗漏，我马上修复

**Comment by chinakids** [comment]
已修复
