### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by danbao** [chinakids/atom-simplified-chinese-menu#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'uri' of undefined

```
At /Users/danbao/.atom/packages/simplified-chinese-menu/lib/main.coffee:27

TypeError: Cannot read property 'uri' of undefined
  at /Users/danbao/.atom/packages/simplified-chinese-menu/lib/main.coffee:27:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:384:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:458:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:46.3.0 golang:goinfo (atom-text-editor.editor.is-focused)
     -0:04.6.0 golang:getmissingtools (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v1.0.0
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.3
go-plus, v3.4.5
project-manager, v1.15.11
simplified-chinese-menu, v3.2.0

# Dev
No dev packages
```

**Comment by danbao** [comment]
关闭最后一个文件的时候会报错

**Comment by chinakids** [comment]
今天稍后我会修复这个问题，请留意更新

**Comment by danbao** [comment]
好的多谢

**Comment by lifehale1993** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Unknown Windows Version
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'uri' of undefined

```
At C:\Users\Administrator\.atom\packages\simplified-chinese-menu\lib\main.coffee:27

TypeError: Cannot read property 'uri' of undefined
  at C:\Users\Administrator\.atom\packages\simplified-chinese-menu\lib\main.coffee:27:14
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:242:22)
  at Pane.module.exports.Pane.removeItem (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:384:16)
  at Pane.module.exports.Pane.destroyItem (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\src\pane.js:458:16)
  at HTMLDivElement.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
  3x -0:27 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:23.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:23.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:17.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "monokai"
    ],
    "disabledPackages": [
      "emmet"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-jade, v0.3.0
atom-material-ui, v0.5.21
atom-minify, v0.2.2
autocomplete-paths, v1.0.2
color-picker, v2.0.11
docblockr, v0.7.3
file-icons, v1.6.6
highlight-line, v0.11.0
language-jade, v0.6.2
linter, v1.4.3
minimap, v4.12.3
monokai, v0.18.0
pigments, v0.11.0
pretty-json, v0.4.1
simplified-chinese-menu, v3.2.0
status-bar, v0.78.0

# Dev
No dev packages
```
me too, for help.

**Comment by chinakids** [comment]
你好，本问题已经被修复，但是apm发布出了问题，没办法发布，正在和官方沟通中，你也可以自行修复错误，参照这里https://github.com/chinakids/atom-simplified-chinese-menu/blob/master/lib/main.coffee ，对于给你们造成的不便十分抱歉(⁄ ⁄•⁄ω⁄•⁄ ⁄)ྉྉྉ羞羞哒

**Comment by chinakids** [comment]
补充:这个问题并非致命性问题，可以忽略，等发布工具正常后将发布更新，并关闭此问题

**Comment by lifehale1993** [comment]
支持你！！

**Comment by chinakids** [comment]
已经修复，请前往更新
