### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by ywfwj2008** [chinakids/atom-simplified-chinese-menu#23]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.4
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.4.11
### Stack Trace

Uncaught TypeError: Cannot read property 'getAttribute' of null

```
At /Users/fuwenji/.atom/packages/simplified-chinese-menu/lib/main.coffee:33

TypeError: Cannot read property 'getAttribute' of null
    at /Users/fuwenji/.atom/packages/simplified-chinese-menu/lib/main.coffee:33:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:255:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:319:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:467:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:532:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:622:17)
```
### Commands

```
     -1:01.5.0 tree-view:remove-project-folder (div.header.list-item)
     -0:46.2.0 window:install-shell-commands (div.pane-item.native-key-bindings.about)
     -0:22.4.0 bracket-matcher:go-to-matching-bracket (div.pane-item.native-key-bindings.about)
     -0:15.5.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:13.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.1.1
language-docker, v1.1.6
minimap, v4.21.0
pigments, v0.24.5
simplified-chinese-menu, v3.4.11
sublime-panes, v0.2.5

# Dev
No dev packages
```

**Comment by 2015-lizaiyang** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package 3.5.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getAttribute' of null

```
At C:\Users\lizaiyang\.atom\packages\atom-simplified-chinese-menu-master\lib\main.coffee:33

TypeError: Cannot read property 'getAttribute' of null
    at /packages/atom-simplified-chinese-menu-master/lib/main.coffee:33:38
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
    at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/app.asar/node_modules/tabs/lib/tab-bar-view.js:738:16)
    at TabBarView.module.exports.TabBarView.onDrop (/app.asar/node_modules/tabs/lib/tab-bar-view.js:622:23)
```

### Commands

```
     -2:51.7.0 core:select-all (input.hidden-input)
     -2:51.4.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
simplified-chinese-menu 3.5.0 
language-vue 0.21.2 
autocomplete-paths 1.0.5 
build 0.67.0 
build-sass 0.10.1 
busy 0.7.0 
docblockr 0.9.1 
emmet 2.4.3 
file-icons 2.0.17 
highlight-selected 0.12.0 
minimap 4.26.8 
pigments 0.39.0 
tag 0.4.0 
terminal-plus 0.14.5 
```

**Comment by sonictuzi** [comment]
why you send to me




------------------ 原始邮件 ------------------
发件人: "lizaiyang";<notifications@github.com>;
发送时间: 2017年3月15日(星期三) 下午3:57
收件人: "chinakids/atom-simplified-chinese-menu"<atom-simplified-chinese-menu@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [chinakids/atom-simplified-chinese-menu] Uncaught TypeError:Cannot read property 'getAttribute' of null (#23)




[Enter steps to reproduce:]
  
...
 
...
  
Atom: 1.15.0 x64
 Electron: 1.3.13
 OS: Unknown Windows version
 Thrown From: simplified-chinese-menu package 3.5.0
 
Stack Trace
 
Uncaught TypeError: Cannot read property 'getAttribute' of null
 At C:\Users\lizaiyang\.atom\packages\atom-simplified-chinese-menu-master\lib\main.coffee:33 TypeError: Cannot read property 'getAttribute' of null     at /packages/atom-simplified-chinese-menu-master/lib/main.coffee:33:38     at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)     at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)     at /app.asar/src/pane-container.js:348:27     at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)     at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)     at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)     at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)     at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/app.asar/node_modules/tabs/lib/tab-bar-view.js:738:16)     at TabBarView.module.exports.TabBarView.onDrop (/app.asar/node_modules/tabs/lib/tab-bar-view.js:622:23)  
Commands
      -2:51.7.0 core:select-all (input.hidden-input)      -2:51.4.0 core:paste (input.hidden-input)  
Non-Core Packages
 simplified-chinese-menu 3.5.0  language-vue 0.21.2  autocomplete-paths 1.0.5  build 0.67.0  build-sass 0.10.1  busy 0.7.0  docblockr 0.9.1  emmet 2.4.3  file-icons 2.0.17  highlight-selected 0.12.0  minimap 4.26.8  pigments 0.39.0  tag 0.4.0  terminal-plus 0.14.5

**Comment by chinakids** [comment]
请下载v5.3.2版本已修复
