### ISSUE TITLE
Error: Cannot find module 'cson'

### ISSUE THREAD

**Issue by veky** [chinakids/atom-simplified-chinese-menu#26]
Cannot find module 'cson'
Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at new ChineseSetting (file:///__/.atom/packages/atom-simplified-chinese-menu/lib/main.coffee:4:12)
    at Object.<anonymous> (file:///**/.atom/packages/atom-simplified-chinese-menu/lib/main.coffee:88:22)
    at Object.<anonymous> (file:///**/.atom/packages/atom-simplified-chinese-menu/lib/main.coffee:1:1)
    at Module._compile (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](----AppDataLocalatomapp-1.8.0resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at ----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at ----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:397:19)
    at ----\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:743:28

**Comment by chinakids** [comment]
挂上VPN  或者修改 安装npm install -g mrn  && nrm use taobao 再安装本插件

**Comment by weq1979** [comment]
你好 我想也很想用这个汉化插件 但是同样也是这个错误Cannot find module 'cson' 我是在https://github.com/chinakids/atom-simplified-chinese-menu手动下载并放在C:\Users\weq\.atom\packages下的 ,不太明白你说的 npm install -g nrm && nrm use taobao 是什么意思 我是win10 系统

**Comment by chinakids** [comment]
@weq1979  我刚才上传了一些模块，下载最新的master分支代码即可

**Comment by chinakids** [comment]
请下载v5.3.2版本已修复，新版本中已经移除对CSON的依赖

**Comment by Herycdd** [comment]
我下载官网的最新版本安装完还是有这个问题存在
