### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by haoshuai0913** [chinakids/atom-simplified-chinese-menu#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package 3.5.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At C:\Users\10243\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\decompress-zip\node_modules\graceful-fs\polyfills.js:14

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/app.asar/node_modules/decompress-zip/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/packages/atom-simplified-chinese-menu/node_modules/graceful-fs/polyfills.js:18:9)
    at process.chdir (/packages/npm/node_modules/graceful-fs/polyfills.js:21:9)
    at lint (/packages/atom-jshint/index.js:229:10)
    at complete (/packages/atom-jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/packages/atom-jshint/node_modules/lodash/index.js:7707:11)
```

### Commands

```
  2x -3:26.6.0 core:backspace (input.hidden-input)
     -3:22.2.0 autocomplete-plus:confirm (input.hidden-input)
     -3:20.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:20.7.0 docblockr:parse-enter (input.hidden-input)
     -3:20.7.0 editor:newline (input.hidden-input)
 22x -3:19.7.0 core:backspace (input.hidden-input)
     -3:12.6.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:12.6.0 docblockr:parse-enter (input.hidden-input)
     -3:12.6.0 editor:newline (input.hidden-input)
 33x -3:10.7.0 core:backspace (input.hidden-input)
  2x -2:58 core:save (input.hidden-input)
  5x -1:21.2.0 core:backspace (input.hidden-input)
     -1:12 core:confirm (input.hidden-input)
  3x -1:02.1.0 core:backspace (input.hidden-input)
     -0:58.9.0 core:confirm (input.hidden-input)
  2x -0:51.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
file-icons 2.1.3 
atom-autocomplete-php 0.22.2 
autoprefixer 3.6.1 
atom-beautify 0.29.22 
csslint 1.1.5 
atom-html-preview 0.1.22 
jshint 1.8.6 
atom-live-server 2.1.2 
php-cs-fixer 4.1.0 
simplified-chinese-menu 3.5.0 
atom-ternjs 0.18.2 
autocomplete-java 1.2.5 
autocomplete-paths 1.0.5 
color-picker 2.2.5 
docblockr 0.9.4 
emmet 2.4.3 
local-server-web-view 1.1.0 
minimap 4.27.1 
npm 4.5.0 
open-in-browsers 0.0.19 
```

**Comment by chinakids** [comment]
请下载v5.3.2版本已修复
