### ISSUE TITLE
Failed to load the simplified-chinese-menu package

### ISSUE THREAD

**Issue by neosun100** [chinakids/atom-simplified-chinese-menu#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Unknown Windows Version
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.2.3

### Stack Trace

Failed to load the simplified-chinese-menu package

```
At Cannot find module 'cson'

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new ChineseSetting (C:\Users\Administrator\.atom\packages\simplified-chinese-menu\lib\main.coffee:9:14)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\simplified-chinese-menu\lib\main.coffee:113:20)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\simplified-chinese-menu\lib\main.coffee:115:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
```

### Commands

```
     -0:36.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
simplified-chinese-menu, v3.2.3

# Dev
No dev packages
```

**Comment by jas0ncn** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.11
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.2.3


### Stack Trace

Failed to load the simplified-chinese-menu package

```
At Cannot find module 'cson'

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new ChineseSetting (/Users/Jason/.atom/packages/simplified-chinese-menu/lib/main.coffee:9:14)
    at Object.<anonymous> (/Users/Jason/.atom/packages/simplified-chinese-menu/lib/main.coffee:113:20)
    at Object.<anonymous> (/Users/Jason/.atom/packages/simplified-chinese-menu/lib/main.coffee:115:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.0
bottom-dock, v0.3.1
docblockr, v0.7.3
emmet, v2.3.12
gulp-manager, v0.2.5
simplified-chinese-menu, v3.2.3

# Dev
No dev packages
```

**Comment by chinakids** [comment]
你们好，由于本人失误给你们造成的问题十分抱歉，问题已经提交修复，请更新3.2.4版本

**Comment by Doyle-net** [comment]
![image](https://cloud.githubusercontent.com/assets/7744216/10532294/52ef196e-73ef-11e5-90f8-eed28e87fe8b.png)

**Comment by chinakids** [comment]
请通过apm或者设置里安装 
------------------ Original ------------------

**Comment by Doyle-net** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [emmet](https://github.com/emmetio/emmet-atom) package, v2.3.13


### Stack Trace

Failed to load the emmet package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\铜\.atom\packages\emmet\lib\emmet.coffee:5:9)
  at Object.<anonymous> (C:\Users\铜\.atom\packages\emmet\lib\emmet.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:667:21)
  at Object.<anonymous> (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\铜\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///C:/Users/%E9%93%9C/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///C:/Users/%E9%93%9C/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.11
autocomplete-html-entities, v0.1.0
emmet, v2.3.13
simplified-chinese-menu, v3.3.5

# Dev
No dev packages
```

**Comment by chinakids** [comment]
你是怎么装的？ 
------------------ Original ------------------

**Comment by Doyle-net** [comment]
通过atom里面安装的

**Comment by chinakids** [comment]
卸载后重装，有必要的话请挂上vpn 
------------------ Original ------------------

**Comment by Doyle-net** [comment]
更新到最新版本就出现这个问题了

**Comment by zouliyan** [comment]
3.4.11 windows7 64
Cannot find module 'cson'
Hide Stack Trace
Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at new ChineseSetting (file:///C:/Users/Z_Liyan/.atom/packages/atom-simplified-chinese-menu-master/lib/main.coffee:4:12)
    at Object.<anonymous> (file:///C:/Users/Z_Liyan/.atom/packages/atom-simplified-chinese-menu-master/lib/main.coffee:88:22)
    at Object.<anonymous> (file:///C:/Users/Z_Liyan/.atom/packages/atom-simplified-chinese-menu-master/lib/main.coffee:1:1)
    at Module._compile (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\package.js:720:27)
    at C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\package.js:116:28
    at Package.module.exports.Package.measure (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\atom-environment.js:684:21)
    at module.exports (C:\Users\Z_Liyan\AppData\Local\atom\app-1.6.0\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Z_Liyan/AppData/Local/atom/app-1.6.0/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/Z_Liyan/AppData/Local/atom/app-1.6.0/resources/app.asar/static/index.js:41:9)

**Comment by chinakids** [comment]
@zouliyan 
### cson无法安装时因为您所处的网络环境无法连接上npm资源服务器，提供您四种解决方案

- 1.使用VPN代理

- 2.更换NPM源(推荐使用淘宝源)

```
 npm config set registry https://registry.npm.taobao.org
```

然后进入插件目录执行

```
npm install
```

- 3.使用第三方npm工具(cnpm)

```
 [sudo] npm install -g cnpm  --registry=https://registry.npm.taobao.org
```

然后进入插件目录执行

```
cnpm install
```

- 4.使用第三方源管理工具(nrm)

```
[sudo] npm install -g nrm  --registry=https://registry.npm.taobao.org
```

然后进入插件目录执行

```
nrm use taobao && npm install
```

**Comment by zouliyan** [comment]
我用离线安装的不可以么？

**Comment by chinakids** [comment]
@zouliyan 
atom官方并没有提供所谓的‘离线安装功能’
自己拷贝插件代码放入atom插件目录需要在插件目录内执行依赖安装命令

**Comment by chinakids** [comment]
@zouliyan 建议在官方商店搜索插件安装，或者使用apm命令安装需要的插件

**Comment by zouliyan** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Z_Liyan>cd C:\Users\Z_Liyan\.atom\packages

C:\Users\Z_Liyan\.atom\packages>apm install

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp
C:\Users\Z_Liyan\.atom\packages>

我是之前一直用Dreamweave的小白，第一次用Atom，麻烦大触了！

**Comment by chinakids** [comment]
@zouliyan 打开atom, setting -> install    直接搜索simplified-chinese-menu然后install吧   ，win下面的apm我没用过

**Comment by y3093** [comment]
windows系统试了用Atom内部install，一直无法下载；后面直接下载github的代码放packages会报错，报“Cannot find module 'cson'”……

再后来开vpn用Atom的install安装成，可以正常使用。大家最好都用Atom安装吧。
