### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by GEOHOTIOS** [chinakids/atom-simplified-chinese-menu#48]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 54.231.72.227:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/linusTorvalds/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by chinakids** [comment]
你是怎么安装的呢

**Comment by Penguin-G** [comment]
错误同上，等待解决中，，，提示缺少python和c++包

**Comment by chinakids** [comment]
@Penguin-G 上面的这个错误一般是因为GFW屏蔽导致无法连上境外源导致的，你可以尝试下翻墙、修改源或者下载离线包安装，至于你说的缺少python和c++包，本插件并不依赖这两个东西，可能是你atom安装本身有问题

**Comment by Penguin-G** [comment]
好的，感谢

在 2017年11月13日 上午11:18，Geron <notifications@github.com>写道：

**Comment by lao-mo** [comment]
window10 需要管理员身份运行安装

**Comment by RenSLei** [comment]
提示缺少python和c++包，多试几次就ok，我的就是。
