### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by cjmdaixi** [chinakids/atom-simplified-chinese-menu#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.11
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/Jimmy/.atom/packages/simplified-chinese-menu/lib/main.coffee:31

TypeError: Cannot read property 'indexOf' of undefined
  at /Users/Jimmy/.atom/packages/simplified-chinese-menu/lib/main.coffee:31:44
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:314:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-css",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-less",
      "language-mustache",
      "language-perl",
      "language-sass",
      "language-source",
      "language-sql",
      "language-toml",
      "wrap-guide",
      "tree-view"
    ],
    "themes": [
      "unity-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.3
ever-notedown, v0.2.11
language-cmake, v0.1.4
language-latex, v0.6.1
language-qtpro, v0.5.0
simplified-chinese-menu, v3.3.2
unity-ui, v2.1.1

# Dev
No dev packages
```

**Comment by chinakids** [comment]
感谢您提交的问题 ,现已提交修复，请卸载后充新安装最新版本即可。
