### ISSUE TITLE
Can't install Chinese language package

### ISSUE THREAD

**Issue by qianweighost** [chinakids/atom-simplified-chinese-menu#52]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04.3
**Thrown From**: [simplified-chinese-menu](https://github.com/chinakids/atom-simplified-chinese-menu) package, v3.4.11

### Stack Trace

Failed to load the simplified-chinese-menu package

```
At Cannot find module 'cson'

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at new ChineseSetting (/home/qianwei/.atom/packages/atom-simplified-chinese-menu-master/lib/main.coffee:4:12)
    at Object.<anonymous> (/home/qianwei/.atom/packages/atom-simplified-chinese-menu-master/lib/main.coffee:88:22)
    at Object.<anonymous> (/home/qianwei/.atom/packages/atom-simplified-chinese-menu-master/lib/main.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:715:27)
    at /opt/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/opt/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.disablePackage (/opt/atom/resources/app.asar/src/package-manager.js:176:19)
    at HTMLButtonElement.<anonymous> (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:330:27)
    at HTMLButtonElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  4x -0:36.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by LiXinbo2017** [comment]
I met with the same case and is there any solution to it?
